name: hannahjane
favicon: null
layout_spectrum: 0.5772618190385401
typography_spectrum: 0.02844162588007748
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.6998649095185101
  lightness: 0.47674660780467093
  saturation: 0.9158120031934232
  rhythmicContrast: 0.04124520695768297
purpose: []
